CREATE DATABASE ecommerce ;
USE ecommerce ;

RENAME TABLE geolocatio to geolocation ;

-- Basic Queries
-- 1. List all unique cities where customers are located.

SELECT DISTINCT customer_city FROM customers ; 

-- 2. Count the number of orders placed in 2017.

SELECT COUNT(*) AS orders_in_2017 FROM orders 
where year(order_purchase_timestamp) = 2017 ;

-- 2.1 Count the number of orders placed in 2018
SELECT COUNT(*) AS orders_in_2018 FROM orders 
where year(order_purchase_timestamp) = 2018 ;

-- 3. Find the total sales per category.
SELECT pd.product_category as category , round(sum(oi.price + oi.freight_value) , 2) as Total_Sales 
FROM order_items oi 
JOIN products pd
ON oi.product_id = pd.product_id 
GROUP BY category 
ORDER BY Total_Sales  DESC; 



-- 4. Calculate the percentage of orders that were paid in installments.
SELECT (COUNT(p.payment_installments)  * 100) / count(o.order_id) as percentage_installment_ratio
FROM orders o 
JOIN payments p 
ON o.order_id = p.order_id ;


-- 5. Count the number of customers from each state. 
SELECT 	customer_state as state , COUNT(*) AS no_of_customers 
FROM customers 
GROUP BY state 
ORDER BY no_of_customers DESC ;


-- Intermediate Queries

-- 1. Calculate the number of orders per month in 2018.
SELECT MONTH(order_purchase_timestamp) as month_number , monthname(order_purchase_timestamp) as month_name , count(*) as no_of_orders 
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2018 
GROUP BY month_number , month_name 
ORDER BY month_number;

-- 1.2 Calculate the number of orders per month in 2017
SELECT MONTH(order_purchase_timestamp) as month_number , monthname(order_purchase_timestamp) as month_name , count(*) as no_of_orders 
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2017
GROUP BY month_number , month_name 
ORDER BY month_number;



-- 2. Find the average number of products per order, grouped by customer city.


-- 3. Calculate the percentage of total revenue contributed by each product category.
-- 4. Identify the correlation between product price and the number of times a product has been purchased.
-- 5. Calculate the total revenue generated by each seller, and rank them by revenue.

-- Advanced Queries
-- 1. Calculate the moving average of order values for each customer over their order history.
-- 2. Calculate the cumulative sales per month for each year.
-- 3. Calculate the year-over-year growth rate of total sales.
-- 4. Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase.
-- 5. Identify the top 3 customers who spent the most money in each year.